Auth rework code enhancements
medox-eu/monorepo pull request #95
Opened 2021-09-12 01:50 UTC by PaulMonnery

2021-09-12 02:11 UTC, Skerilyo requested changes

2021-09-12 02:11 UTC, Skerilyo commented on donald/src/auth/auth.controller.ts
> -  @Post('validator')
Pourquoi ça a été suppr ?

2021-09-12 02:11 UTC, Skerilyo commented on donald/src/auth/auth.service.ts
> -  // eslint-disable-next-line class-methods-use-this
Idem

2021-09-12 02:11 UTC, Skerilyo commented on donald/src/auth/dto/validatorInput.dto.ts
> -import { IsNotEmpty } from 'class-validator';
Same ?

2021-09-12 02:11 UTC, Skerilyo commented on donald/src/auth/dto/validatorOutput.dto.ts
> -import { ApiProperty } from '@nestjs/swagger';
Same ?

2021-09-12 02:11 UTC, Skerilyo commented on donald/src/auth/dto/verifMail.ts
> -
Same ?

2021-09-12 02:13 UTC, PaulMonnery commented on donald/src/auth/auth.controller.ts
> -  @Post('validator')
je croyais que la route validator (et les DTO etc tout ce qui s'en rapproche) avaient été supprimés pck tu avais fait directement dans la route register, si c'est encore utile je revert les fichiers tkt

2021-09-12 02:13 UTC, PaulMonnery commented on donald/src/auth/auth.service.ts
> -  // eslint-disable-next-line class-methods-use-this
j'ai ajouté la regle au eslint yaml directement

2021-09-12 02:13 UTC, PaulMonnery commented on donald/src/auth/dto/validatorInput.dto.ts
> -import { IsNotEmpty } from 'class-validator';
je croyais que la route validator (et les DTO etc tout ce qui s'en rapproche) avaient été supprimés pck tu avais fait directement dans la route register, si c'est encore utile je revert les fichiers tkt

2021-09-12 02:14 UTC, PaulMonnery commented on donald/src/auth/dto/validatorOutput.dto.ts
> -import { ApiProperty } from '@nestjs/swagger';
je croyais que la route validator (et les DTO etc tout ce qui s'en rapproche) avaient été supprimés pck tu avais fait directement dans la route register, si c'est encore utile je revert les fichiers tkt

2021-09-12 02:14 UTC, PaulMonnery commented on donald/src/auth/dto/verifMail.ts
> -
pas besoin de dto, un simple query decorator de nest fait l'affaire, dto c'est surtout pour les body, la y a pas de verification je crois

2021-09-13 12:35 UTC, Skerilyo approved these changes

2021-09-13 12:35 UTC, merged